import type { Express, Request, Response } from "express";
import { and, desc, eq } from "drizzle-orm";
import { getDb } from "./db";
import { bidCancellationRequests, listingsOwned, proxyBids, users } from "../drizzle/schema";
import { getAppUser } from "./appAuth";
import { createNotification, settleExpiredAuctions } from "./notifications";

const requireUser = async (req: Request, res: Response) => {
  const user = await getAppUser(req);
  if (!user) { res.status(401).json({ ok: false, error: "Please log in to use your wallet." }); return undefined; }
  return user;
};
const pesos = (cents: number) => `₱${(cents / 100).toLocaleString("en-PH")}`;
const activeForListing = async (db: NonNullable<Awaited<ReturnType<typeof getDb>>>, listingId: string) => db.select().from(proxyBids).where(and(eq(proxyBids.listingId, listingId), eq(proxyBids.status, "active")));
const auctionStatus = (row: typeof proxyBids.$inferSelect, listing: typeof listingsOwned.$inferSelect) => {
  const ended = Boolean(listing.auctionEndAt && listing.auctionEndAt.getTime() <= Date.now());
  return { auctionState: ended ? "Auction ended" : "Auction ongoing", bidderStatus: ended ? row.status === "won" ? "Won" : "Lost" : row.status === "active" && row.currentBidCents > 0 ? "Winning" : "Losing" };
};

export async function getBidHistoryForUser(userId: number) {
  const db = await getDb();
  if (!db) return [];
  await settleExpiredAuctions();
  const rows = await db.select().from(proxyBids).where(eq(proxyBids.userId, userId)).orderBy(desc(proxyBids.createdAt)).limit(100);
  const listingRows = await db.select().from(listingsOwned);
  const listingMap = new Map(listingRows.map((listing) => [listing.listingId, listing]));
  return rows.map((row) => {
    const listing = listingMap.get(row.listingId);
    const state = listing ? auctionStatus(row, listing) : { auctionState: "Auction ended", bidderStatus: "Lost" };
    return { ...row, listingTitle: listing?.title ?? row.listingId, listingType: listing?.listingType ?? "Auction", auctionEndAt: listing?.auctionEndAt?.toISOString() ?? null, ...state };
  });
}

export function registerBiddingRoutes(app: Express) {
  app.get("/api/wallet", async (req, res) => { const user = await requireUser(req, res); if (!user) return; return res.json({ ok: true, walletCents: user.walletCents }); });
  app.post("/api/wallet/fund", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const amountCents = Math.round(Number(req.body?.amountCents)); if (!Number.isFinite(amountCents) || amountCents < 10000 || amountCents > 100000000) return res.status(400).json({ ok: false, error: "Demo top-ups must be between ₱100 and ₱1,000,000." }); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const nextBalance = user.walletCents + amountCents; await db.update(users).set({ walletCents: nextBalance }).where(eq(users.id, user.id)); return res.json({ ok: true, walletCents: nextBalance }); });
  app.get("/api/bids/history", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const listingId = String(req.query.listingId ?? ""); if (!listingId) return res.status(400).json({ ok: false, error: "listingId is required." }); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, listingId)).limit(1))[0]; if (!listing) return res.status(404).json({ ok: false, error: "Auction listing not found." }); const isSeller = user.role === "admin" || listing.ownerId === user.id; const rows = await db.select().from(proxyBids).where(eq(proxyBids.listingId, listingId)).orderBy(desc(proxyBids.createdAt)).limit(50); const history = await Promise.all(rows.map(async (row) => { const bidder = (await db.select({ name: users.name, email: users.email }).from(users).where(eq(users.id, row.userId)).limit(1))[0]; const amountCents = row.currentBidCents || row.maxBidCents || 0; return { ...row, amountCents, bidder: bidder?.name || bidder?.email || `Bidder ${row.userId}`, listingTitle: listing.title }; })); return res.json({ ok: true, listingId, viewer: isSeller ? "seller" : "buyer", history }); });
  app.get("/api/bids/my-history", async (req, res) => { const user = await requireUser(req, res); if (!user) return; return res.json({ ok: true, history: await getBidHistoryForUser(user.id) }); });
  app.get("/api/bids/stream", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const listingId = String(req.query.listingId ?? ""); if (!listingId) return res.status(400).json({ ok: false, error: "listingId is required." }); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); res.setHeader("Content-Type", "text/event-stream"); res.setHeader("Cache-Control", "no-cache"); res.setHeader("Connection", "keep-alive"); const publish = async () => { const rows = await activeForListing(db, listingId); const currentBidCents = rows.reduce((highest, row) => Math.max(highest, row.currentBidCents), 0); res.write(`data: ${JSON.stringify({ listingId, currentBidCents, activeBids: rows.length, updatedAt: new Date().toISOString() })}\n\n`); }; await publish(); const timer = setInterval(publish, 2000); req.on("close", () => clearInterval(timer)); });
  app.get("/api/bids/current", async (req, res) => { await settleExpiredAuctions(); const listingId = String(req.query.listingId ?? ""); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const rows = await activeForListing(db, listingId); const currentBidCents = rows.reduce((highest, row) => Math.max(highest, row.currentBidCents), 0); return res.json({ ok: true, listingId, currentBidCents, hasBids: rows.length > 0 }); });
  app.get("/api/bids/summary", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const listingId = String(req.query.listingId ?? ""); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, listingId)).limit(1))[0]; if (!listing) return res.status(404).json({ ok: false, error: "Auction listing not found." }); if (user.role !== "admin" && listing.ownerId !== user.id) return res.status(403).json({ ok: false, error: "Only the seller can view the auction summary." }); const rows = await db.select().from(proxyBids).where(eq(proxyBids.listingId, listingId)).orderBy(desc(proxyBids.currentBidCents), desc(proxyBids.createdAt)); const leader = rows.find((row) => row.status === "active") ?? rows[0]; const leaderUser = leader ? (await db.select({ name: users.name }).from(users).where(eq(users.id, leader.userId)).limit(1))[0] : undefined; return res.json({ ok: true, listingId, bidCount: rows.length, activeBidCount: rows.filter((row) => row.status === "active").length, currentBidCents: leader?.currentBidCents ?? listing.priceCents, leadingBidder: leader ? { userId: leader.userId, name: leaderUser?.name ?? `Bidder ${leader.userId}`, status: leader.status, maxBidCents: leader.maxBidCents } : null }); });
  app.get("/api/bids/proxy", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const listingId = String(req.query.listingId ?? ""); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const rows = await db.select().from(proxyBids).where(and(eq(proxyBids.userId, user.id), eq(proxyBids.listingId, listingId), eq(proxyBids.status, "active"))).limit(1); const all = await activeForListing(db, listingId); const currentBidCents = all.reduce((highest, row) => Math.max(highest, row.currentBidCents), 0); return res.json({ ok: true, proxy: rows[0] ?? null, walletCents: user.walletCents, currentBidCents }); });
  app.post("/api/bids/proxy", async (req, res) => {
    const user = await requireUser(req, res); if (!user) return;
    const listingId = String(req.body?.listingId ?? ""); const mode = req.body?.mode === "simple" ? "simple" : "proxy"; const initialBidCents = Math.round(Number(req.body?.bidCents)); let maxBidCents = Math.round(Number(req.body?.maxBidCents)); let incrementCents = Math.round(Number(req.body?.incrementCents));
    if (!listingId || !Number.isFinite(initialBidCents) || initialBidCents <= 0 || (mode === "proxy" && (!Number.isFinite(maxBidCents) || !Number.isFinite(incrementCents) || incrementCents < 100))) return res.status(400).json({ ok: false, error: mode === "simple" ? "Enter a valid bid amount." : "Listing, max bid, and an increment of at least ₱1 are required." });
    if (maxBidCents > user.walletCents) return res.status(400).json({ ok: false, error: `Your max bid cannot exceed your e-wallet balance of ${pesos(user.walletCents)}.` });
    const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." });
    const listing = (await db.select({ ownerId: listingsOwned.ownerId, listingType: listingsOwned.listingType, stock: listingsOwned.stock, priceCents: listingsOwned.priceCents, auctionEndAt: listingsOwned.auctionEndAt, title: listingsOwned.title, minimumIncrementCents: listingsOwned.minimumIncrementCents, antiSnipeSeconds: listingsOwned.antiSnipeSeconds }).from(listingsOwned).where(eq(listingsOwned.listingId, listingId)).limit(1))[0];
    if (!listing) return res.status(404).json({ ok: false, error: "Auction listing not found." });
    if (listing.ownerId === user.id) return res.status(403).json({ ok: false, error: "You cannot bid on your own listing." });
    if (listing.listingType !== "Auction" && listing.listingType !== "Both") return res.status(409).json({ ok: false, error: "This listing is not available for auction bidding." });
    if (listing.stock <= 0) return res.status(409).json({ ok: false, error: "This auction is out of stock and cannot accept bids." });
    if (listing.auctionEndAt && listing.auctionEndAt.getTime() <= Date.now()) return res.status(409).json({ ok: false, error: "This auction has ended." });
    const active = await activeForListing(db, listingId);
    const currentBidCents = active.reduce((highest, row) => Math.max(highest, row.currentBidCents), listing.priceCents);
    const sellerMinimumIncrement = Math.max(100, listing.minimumIncrementCents ?? 100);
    if (mode === "simple") { maxBidCents = initialBidCents; incrementCents = sellerMinimumIncrement; }
    if (incrementCents < sellerMinimumIncrement) return res.status(400).json({ ok: false, error: `Your increment must be at least the seller baseline of ${pesos(sellerMinimumIncrement)}.` });
    const requiredBid = currentBidCents + sellerMinimumIncrement;
    if (maxBidCents < requiredBid) { await createNotification(user.id, "system", "Proxy bid limit reached", `The next bid would be ${pesos(requiredBid)}, above your maximum of ${pesos(maxBidCents)}. Increase your maximum bid to continue.`, listingId); return res.status(409).json({ ok: false, error: `Your maximum bid is below the next increment of ${pesos(requiredBid)}.`, limitReached: true }); }
    if (maxBidCents < initialBidCents) return res.status(400).json({ ok: false, error: "Your maximum bid must be at least your opening bid." });
    if (!Number.isFinite(initialBidCents) || initialBidCents < requiredBid) return res.status(400).json({ ok: false, error: `Your bid must be at least ${pesos(requiredBid)}.` });
    const antiSnipeSeconds = Math.max(0, listing.antiSnipeSeconds ?? 0);
    const remainingSeconds = listing.auctionEndAt ? Math.floor((listing.auctionEndAt.getTime() - Date.now()) / 1000) : Number.MAX_SAFE_INTEGER;
    if (antiSnipeSeconds > 0 && remainingSeconds > 0 && remainingSeconds <= antiSnipeSeconds) {
      const extendedEnd = new Date(listing.auctionEndAt!.getTime() + antiSnipeSeconds * 1000);
      await db.update(listingsOwned).set({ auctionEndAt: extendedEnd, settledAt: null }).where(eq(listingsOwned.listingId, listingId));
      listing.auctionEndAt = extendedEnd;
      await createNotification(listing.ownerId, "system", "Auction extended", `A last-second bid extended “${listing.title}” by ${antiSnipeSeconds} seconds.`, listingId);
    }
    await db.update(proxyBids).set({ status: "outbid", currentBidCents: 0 }).where(and(eq(proxyBids.listingId, listingId), eq(proxyBids.userId, user.id), eq(proxyBids.status, "active")));
    const [created] = await db.insert(proxyBids).values({ userId: user.id, listingId, maxBidCents, incrementCents: Math.max(incrementCents, sellerMinimumIncrement), currentBidCents: initialBidCents, status: "active" }).$returningId();
    const proxies = await activeForListing(db, listingId);
    proxies.sort((a, b) => b.maxBidCents - a.maxBidCents || a.id - b.id);
    const winner = proxies[0]; const runner = proxies[1];
    const winningCurrent = Math.min(winner.maxBidCents, Math.max(initialBidCents, runner ? runner.maxBidCents + winner.incrementCents : initialBidCents));
    await db.update(proxyBids).set({ status: "outbid", currentBidCents: 0 }).where(and(eq(proxyBids.listingId, listingId), eq(proxyBids.status, "active")));
    await db.update(proxyBids).set({ status: "active", currentBidCents: winningCurrent }).where(eq(proxyBids.id, winner.id));
    for (const proxy of proxies) {
      if (proxy.id === winner.id) await createNotification(proxy.userId, "system", "You are winning", `You are currently winning “${listing.title}” at ${pesos(winningCurrent)}. Automatic bidding is active up to ${pesos(proxy.maxBidCents)}.`, listingId);
      else await createNotification(proxy.userId, "system", "You were outbid", `Your bid on “${listing.title}” is losing at ${pesos(winningCurrent)}. Increase your maximum bid to continue.`, listingId);
    }
    const row = (await db.select().from(proxyBids).where(eq(proxyBids.id, created.id)).limit(1))[0];
    return res.json({ ok: true, proxy: row, walletCents: user.walletCents, currentBidCents: winningCurrent, leadingUserId: winner.userId });
  });
  app.post("/api/bids/:bidId/cancel", async (req, res) => { const user = await requireUser(req, res); if (!user) return; await settleExpiredAuctions(); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const bid = (await db.select().from(proxyBids).where(and(eq(proxyBids.id, Number(req.params.bidId)), eq(proxyBids.userId, user.id))).limit(1))[0]; if (!bid || bid.status !== "won") return res.status(404).json({ ok: false, error: "Only your won auction can be cancelled here." }); await db.update(proxyBids).set({ status: "cancelled", currentBidCents: 0 }).where(eq(proxyBids.id, bid.id)); const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, bid.listingId)).limit(1))[0]; const runner = (await db.select().from(proxyBids).where(and(eq(proxyBids.listingId, bid.listingId), eq(proxyBids.status, "outbid"))).orderBy(desc(proxyBids.maxBidCents), desc(proxyBids.createdAt)).limit(1))[0]; if (runner && listing) await createNotification(runner.userId, "system", "Second-chance offer", `The winner cancelled “${listing.title}”. You can accept the auction at ${pesos(runner.maxBidCents)}.`, bid.listingId); return res.json({ ok: true, secondChanceUserId: runner?.userId ?? null }); });
  app.post("/api/bids/:bidId/cancellation-request", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const reason = String(req.body?.reason ?? "").trim().slice(0, 500); if (!reason) return res.status(400).json({ ok: false, error: "A cancellation reason is required." }); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const bid = (await db.select().from(proxyBids).where(and(eq(proxyBids.id, Number(req.params.bidId)), eq(proxyBids.userId, user.id))).limit(1))[0]; if (!bid || bid.status !== "active") return res.status(409).json({ ok: false, error: "Only an active bid can be submitted for cancellation." }); const existing = (await db.select().from(bidCancellationRequests).where(and(eq(bidCancellationRequests.bidId, bid.id), eq(bidCancellationRequests.status, "pending"))).limit(1))[0]; if (existing) return res.json({ ok: true, request: existing, existing: true }); const result = await db.insert(bidCancellationRequests).values({ bidId: bid.id, listingId: bid.listingId, userId: user.id, reason }).$returningId(); const request = (await db.select().from(bidCancellationRequests).where(eq(bidCancellationRequests.id, result[0].id)).limit(1))[0]; const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, bid.listingId)).limit(1))[0]; if (listing) await createNotification(listing.ownerId, "system", "Bid cancellation request", `A buyer requested cancellation for “${listing.title}”: ${reason}`, bid.listingId); return res.status(201).json({ ok: true, request }); });
  app.get("/api/bids/cancellation-requests", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const all = await db.select().from(bidCancellationRequests); const owned = user.role === "admin" ? all : all.filter((request) => request.userId === user.id || request.listingId); const ownedListings = user.role === "admin" ? new Set(all.map((request) => request.listingId)) : new Set((await db.select({ listingId: listingsOwned.listingId }).from(listingsOwned).where(eq(listingsOwned.ownerId, user.id))).map((row) => row.listingId)); return res.json({ ok: true, requests: owned.filter((request) => user.role === "admin" || request.userId === user.id || ownedListings.has(request.listingId)) }); });
  app.patch("/api/bids/cancellation-requests/:requestId", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const request = (await db.select().from(bidCancellationRequests).where(eq(bidCancellationRequests.id, Number(req.params.requestId))).limit(1))[0]; if (!request) return res.status(404).json({ ok: false, error: "Cancellation request not found." }); const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, request.listingId)).limit(1))[0]; if (user.role !== "admin" && listing?.ownerId !== user.id) return res.status(403).json({ ok: false, error: "Only the seller or an admin can decide this request." }); const status = req.body?.status === "approved" ? "approved" : req.body?.status === "denied" ? "denied" : null; if (!status) return res.status(400).json({ ok: false, error: "Status must be approved or denied." }); await db.update(bidCancellationRequests).set({ status }).where(eq(bidCancellationRequests.id, request.id)); if (status === "approved") await db.update(proxyBids).set({ status: "cancelled", currentBidCents: 0 }).where(eq(proxyBids.id, request.bidId)); await createNotification(request.userId, "system", `Bid cancellation ${status}`, `Your bid cancellation request for “${listing?.title ?? request.listingId}” was ${status}.`, request.listingId); return res.json({ ok: true, status }); });
  app.post("/api/bids/second-chance/accept", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const listingId = String(req.body?.listingId ?? ""); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const runner = (await db.select().from(proxyBids).where(and(eq(proxyBids.listingId, listingId), eq(proxyBids.userId, user.id), eq(proxyBids.status, "outbid"))).orderBy(desc(proxyBids.maxBidCents), desc(proxyBids.createdAt)).limit(1))[0]; if (!runner) return res.status(404).json({ ok: false, error: "No second-chance offer is available for this account." }); const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, listingId)).limit(1))[0]; await db.update(proxyBids).set({ status: "won", currentBidCents: runner.maxBidCents }).where(eq(proxyBids.id, runner.id)); if (listing) { await createNotification(listing.ownerId, "auction_won", "Second-chance offer accepted", `The second-highest bidder accepted “${listing.title}” at ${pesos(runner.maxBidCents)}.`, listingId); await createNotification(user.id, "auction_won", "Second-chance offer accepted", `You accepted “${listing.title}” at ${pesos(runner.maxBidCents)}.`, listingId); } return res.json({ ok: true, listingId, status: "won" }); });
  app.post("/api/bids/second-chance/decline", async (req, res) => { const user = await requireUser(req, res); if (!user) return; const listingId = String(req.body?.listingId ?? ""); const db = await getDb(); if (!db) return res.status(503).json({ ok: false, error: "Database is not available yet." }); const runner = (await db.select().from(proxyBids).where(and(eq(proxyBids.listingId, listingId), eq(proxyBids.userId, user.id), eq(proxyBids.status, "outbid"))).orderBy(desc(proxyBids.maxBidCents), desc(proxyBids.createdAt)).limit(1))[0]; if (!runner) return res.status(404).json({ ok: false, error: "No second-chance offer is available for this account." }); const listing = (await db.select().from(listingsOwned).where(eq(listingsOwned.listingId, listingId)).limit(1))[0]; await db.update(proxyBids).set({ status: "cancelled", currentBidCents: 0 }).where(eq(proxyBids.id, runner.id)); if (listing) await createNotification(listing.ownerId, "system", "Second-chance offer declined", `The second-highest bidder declined “${listing.title}”. You can re-auction the item from Inventory.`, listingId); return res.json({ ok: true, listingId, status: "declined" }); });
}
